name: Weekly Railway
on:
    schedule:
        - cron: "0 0 * * 1"
    workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Server 1
        run: |
          curl -X POST https://backboard.railway.com/graphql/v2 \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"query":"mutation serviceInstanceRedeploy($serviceId: String!, $environmentId: String!) {serviceInstanceRedeploy(serviceId: $serviceId, environmentId: $environmentId)}","variables":{"serviceId":"${{ secrets.RAILWAY_SERVICE_1 }}","environmentId":"${{ secrets.RAILWAY_ENV_1 }}"}}' \
      - name: Server 2
        run: |
          curl -X POST https://backboard.railway.com/graphql/v2 \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"query":"mutation serviceInstanceRedeploy($serviceId: String!, $environmentId: String!) {serviceInstanceRedeploy(serviceId: $serviceId, environmentId: $environmentId)}","variables":{"serviceId":"${{ secrets.RAILWAY_SERVICE_2 }}","environmentId":"${{ secrets.RAILWAY_ENV_1 }}"}}' \
          > /dev/null 2>&1
      - name: Server 3
        run: |
          curl -X POST https://backboard.railway.com/graphql/v2 \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"query":"mutation serviceInstanceRedeploy($serviceId: String!, $environmentId: String!) {serviceInstanceRedeploy(serviceId: $serviceId, environmentId: $environmentId)}","variables":{"serviceId":"${{ secrets.RAILWAY_SERVICE_3 }}","environmentId":"${{ secrets.RAILWAY_ENV_1 }}"}}' \
          > /dev/null 2>&1
      - name: Server 4
        run: |
          curl -X POST https://backboard.railway.com/graphql/v2 \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"query":"mutation serviceInstanceRedeploy($serviceId: String!, $environmentId: String!) {serviceInstanceRedeploy(serviceId: $serviceId, environmentId: $environmentId)}","variables":{"serviceId":"${{ secrets.RAILWAY_SERVICE_4 }}","environmentId":"${{ secrets.RAILWAY_ENV_1 }}"}}' \
          > /dev/null 2>&1
      - name: Server 5
        run: |
          curl -X POST https://backboard.railway.com/graphql/v2 \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"query":"mutation serviceInstanceRedeploy($serviceId: String!, $environmentId: String!) {serviceInstanceRedeploy(serviceId: $serviceId, environmentId: $environmentId)}","variables":{"serviceId":"${{ secrets.RAILWAY_SERVICE_5 }}","environmentId":"${{ secrets.RAILWAY_ENV_1 }}"}}' \
          > /dev/null 2>&1
      - name: Server 6
        run: |
          curl -X POST https://backboard.railway.com/graphql/v2 \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN_2 }}" \
          -H "Content-Type: application/json" \
          -d '{"query":"mutation serviceInstanceRedeploy($serviceId: String!, $environmentId: String!) {serviceInstanceRedeploy(serviceId: $serviceId, environmentId: $environmentId)}","variables":{"serviceId":"${{ secrets.RAILWAY_SERVICE_6 }}","environmentId":"${{ secrets.RAILWAY_ENV_2 }}"}}' \
          > /dev/null 2>&1
